#pragma once
#include "windows.h"

struct INPUTCONTEXT;
typedef struct INPUTCONTEXT INPUTCONTEXT;

typedef void* HIMC;
typedef void* HIMCC;

typedef struct tagREGISTERWORDA {
    LPSTR lpReading;
    LPSTR lpWord;
} REGISTERWORDA, *PREGISTERWORDA, *LPREGISTERWORDA;

typedef struct tagREGISTERWORDW {
    LPWSTR lpReading;
    LPWSTR lpWord;
} REGISTERWORDW, *PREGISTERWORDW, *LPREGISTERWORDW;

typedef struct tagSTYLEBUFA {
    DWORD dwStyle;
    char  szDescription[32];
} STYLEBUFA, *PSTYLEBUFA, *LPSTYLEBUFA;

typedef struct tagSTYLEBUFW {
    DWORD dwStyle;
    WCHAR szDescription[32];
} STYLEBUFW, *PSTYLEBUFW, *LPSTYLEBUFW;

typedef struct tagCANDIDATELIST {
    DWORD dwSize;
    DWORD dwStyle;
    DWORD dwCount;
    DWORD dwSelection;
    DWORD dwPageStart;
    DWORD dwPageSize;
    DWORD dwOffset[1];
} CANDIDATELIST, *PCANDIDATELIST, *LPCANDIDATELIST;

typedef struct tagCOMPOSITIONFORM {
    DWORD dwStyle;
    POINT ptCurrentPos;
    RECT  rcArea;
} COMPOSITIONFORM, *PCOMPOSITIONFORM, *LPCOMPOSITIONFORM;

typedef struct tagCANDIDATEFORM {
    DWORD dwIndex;
    DWORD dwStyle;
    POINT ptCurrentPos;
    RECT  rcArea;
} CANDIDATEFORM, *PCANDIDATEFORM, *LPCANDIDATEFORM;

#define GCS_COMPREADSTR     0x0001
#define GCS_COMPREADATTR    0x0002
#define GCS_COMPREADCLAUSE  0x0004
#define GCS_COMPSTR         0x0008
#define GCS_COMPATTR        0x0010
#define GCS_COMPCLAUSE      0x0020
#define GCS_CURSORPOS       0x0080
#define GCS_DELTASTART      0x0100
#define GCS_RESULTREADSTR   0x0200
#define GCS_RESULTREADCLAUSE 0x0400
#define GCS_RESULTSTR       0x0800
#define GCS_RESULTCLAUSE    0x1000

#define NI_OPENCANDIDATE    0x0010
#define NI_CLOSECANDIDATE   0x0011
#define NI_SELECTCANDIDATESTR 0x0012
#define NI_CHANGECANDIDATELIST 0x0013
#define NI_FINALIZECONVERSIONSTRING 0x0014
#define NI_COMPOSITIONSTR   0x0015
#define NI_SETCANDIDATE_PAGESTART 0x0016
#define NI_SETCANDIDATE_PAGESIZE 0x0017
#define NI_IMEMENUSELECTED  0x0018

#define CFS_DEFAULT         0x0000
#define CFS_RECT            0x0001
#define CFS_POINT           0x0002
#define CFS_FORCE_POSITION  0x0020
#define CFS_CANDIDATEPOS    0x0040
#define CFS_EXCLUDE         0x0080

#define IMC_GETCANDIDATEPOS 0x0007
#define IMC_SETCANDIDATEPOS 0x0008
#define IMC_GETCOMPOSITIONFONT 0x0009
#define IMC_SETCOMPOSITIONFONT 0x000A
#define IMC_GETCOMPOSITIONWINDOW 0x000B
#define IMC_SETCOMPOSITIONWINDOW 0x000C
#define IMC_GETSTATUSWINDOWPOS 0x000F
#define IMC_SETSTATUSWINDOWPOS 0x0010
#define IMC_CLOSESTATUSWINDOW 0x0021
#define IMC_OPENSTATUSWINDOW 0x0022
